CREATE DEFINER=`tuyendungUser`@`%` PROCEDURE `ETL_Nganh_IT`()
BEGIN
/*Procedure này sẽ update ID_Nganh của các công việc không
    v2.2 2023.12.12*/
	/*Procedure ETL Nganh: 
		1. Lọc các công việc không thuộc IT
		2. Lấy lại những công việc bị phân loại ngoài ngành IT nhưng thực chất là của IT 
  	*/
	/*1. Lọc các công việc không thuộc IT từ phần lọc thô*/ 
	update Stg_ThongTin
	set ID_Nganh = 6 
	where ID_Nganh = 2 
	AND
	(
		TenCV like '%CALL%'
		 or TenCV like '%Video%'
		 or TenCV like '%Chăm sóc%'
		 or TenCV like '%Điều hoà%'
		 or TenCV like '%máy móc%'
		 or TenCV like '%máy đúc%'
		 or TenCV like '%Tư Vấn %'
		 or TenCV like '%Dịch Vụ%'
		 or TenCV like '%Human%'
		 or TenCV like '%Khách Hàng%'
		 or TenCV like '%MARKETING%'
		 or TenCV like '%Digital%'
		 or TenCV like '%Kỹ sư ATE%'
		 or TenCV like '%bảo vệ%'
		 or TenCV like '%hành chính%'
		 or TenCV like '%Cơ Điện %'
		 or TenCV like '%Digital %'
		 or TenCV like '%TRUYỀN THÔNG%'
		 or TenCV like '%Mass%'
		 or TenCV like '%Kinh doanh%'
		 or TenCV like '%Content%'
		 or TenCV like '%Copy%'
		 or TenCV like '%cửa hàng%'
		 or TenCV like '%sự kiện%'
		 or TenCV like '%thợ%'
		 or TenCV like '%Talent%'
		 or TenCV like '%Recruit%'
		 or TenCV like '%Category %'
		 or TenCV like '%điện tử %'
		 or TenCV like '%Consultant%'
		 or TenCV like '%3D%'
		 or TenCV like '%Japanese bse%'
		 or TenCV like '%Sale%'
		 or TenCV like 'sale%'
		 or TenCV like '% Ads %'
		 or TenCV like '%định giá viên%'
		 or TenCV like '%acquisition%'
		 or TenCV like '%Lazada%'
		 or TenCV like '%Supply %'
		 or TenCV like '%CSKH%'
         or TenCV like '%photoshop%'
		 or TenCV like '%Kho %'
		 or TenCV like '%Cơ khí%'
		 or TenCV like '%Thương mại%'
		 or TenCV like '% Điện %'
		 or TenCV like '%Quay dựng%'
		 or TenCV like '%Livestream%'
		 or TenCV like '%Nhiệt%'
		 or TenCV like '%TMĐT%'
		 or TenCV like '%Media%'
		 or TenCV like '%mã QR%'
		 or TenCV like '%Store Manager%'
		 or TenCV like '%editor%'
		 or TenCV like '%tái bảo hiểm%'
		 or TenCV like '% bán hàng %'
		 or TenCV like 'bán hàng %'
		 or TenCV like '%bán hàng %'
		 or TenCV like '% bán hàng'
		 or TenCV like '%SEO%'
		 or TenCV like '%waitstaff%'
		 or TenCV like '%Rạp%'
         or TenCV like '%bao bì%'
         or TenCV like '%sushi%'
         or TenCV like '% thị %'
         or TenCV like '%Báo cáo phân tích%'
         or TenCV like '%thu hút%'
         or TenCV like '%Phiên dịch tiếng Nhật%'
         or TenCV like '%Thiết bị%'
         or TenCV like '%Dược%'
         or TenCV like '%Rạp%'
		 or TenCV like '%Bao bì%'
		 or TenCV like '%Thực phẩm%'
		 or TenCV like '%furniture%'
		 or TenCV like '%Tổng đài%'
		 or TenCV like '%writer%'
		 or TenCV like '%nhập liệu%'
		 or TenCV like '%tuyển sinh%'
		 or TenCV like '%thương hiệu%'
		 or TenCV like '%Corporate%'
		 or TenCV like '%teacher%'
		 or TenCV like '%Furniture%'
		 or TenCV like '%biên tập%'
		 or TenCV like '%account%'
		 or TenCV like '%production monitor%'
		 or TenCV like '%Tổng đài%'
         or TenCV like '%tài chính%'
		 or TenCV like '%Kế toán%'
		 or TenCV like 'Kế toán%'
		 or TenCV like 'Giảng viên%'
		 or TenCV like '%Bác sĩ %'
		 or TenCV like '%Shop%'
		 or TenCV like 'tài xế%'
		 or TenCV like '%Retail%'
		 or TenCV like '%Medical%'
		 or TenCV like '%Wood%'
		 or TenCV like '%Draw%'
		 or TenCV like '%AutoCAD%'
		 or TenCV like '%TikTok%'
		 or TenCV like 'Litigation %'
		 or TenCV like '%Invest%'
		 or TenCV like '%trưng bày'
		 or TenCV like 'IE Engineer'
		 or TenCV like '% Đăng ký'
		 or TenCV like '%Purchas%'
		 or TenCV like 'Mechanical%'
		 or TenCV like '%Pháp lý%'
		 or TenCV like '%Chi tiêu%'
		 or TenCV like '% HR %'
		 or TenCV like 'Main%'
		 or TenCV like '%Giám%' -- Lọc các tin giám định, giám sát, (giám đốc) nếu đăng tin IT chuẩn thì sẽ đăng CTO...AFTER
		 or TenCV like '%định%' -- Tỷ lệ tin IT bị dính vào khá ít 
		 or TenCV like '%bank%'
		 or TenCV like '%Thanh toán%'
		 or TenCV like '%Audit%'
		 or TenCV like '%trainer%'
		 or TenCV like '%thư ký%'
		 or TenCV like '%bánh kẹo%'
		 or TenCV like '%bảo trì%'
		 or TenCV like '% trải %' -- trải nghiệm
		 or TenCV like '%campaign%'
		 or TenCV like '%kiểm soát%' 
		 or TenCV like '%kĩ sư hoá%'
		 or TenCV like '% Nợ %'
		 or TenCV like '% lái %' -- lái xe
		 or TenCV like '% Nợ %'
		);


	/*2. Lấy lại những công việc bị phân loại ngoài ngành IT nhưng thực chất là của IT */
	update Stg_ThongTin
    set ID_Nganh = 2
    where ID_Nganh = 6
	AND
		(
		 TenCV like '%IT%'
		or TenCV like '%Technical%'
		or TenCV like '%desk%'	
		or TenCV like '%Architect%'
		or TenCV like '%CNTT%'		
		or TenCV like '%Dữ liệu%'
		or TenCV like '%Java%'
		or TenCV like '%Engineer%'
		or TenCV like '%Kuberrnets%'
		or TenCV like '%Docker%'
		or TenCV like '%.Net%'
		or TenCV like '%Back%'
		or TenCV like '%Python%'

--
		 or lower(TenCV) like '%lập trình%'
		 or TenCV like '%Front%'
		 or TenCV like 'Front%'
		 or TenCV like '%Devops%'
		 or TenCV like '%Mobile Developer%'
		 or TenCV like '%Product Development%'
		 or TenCV like '%Dev%'
		 or TenCV like '%Fullstack%'
		 or TenCV like '%FullStack%'
		 or TenCV like '%Unity%'
		 or TenCV like '%WordPpress%'
		  or TenCV like '%PHP %'
--
		or TenCV like '%Software%'
		or TenCV like '%ERP%'
		or TenCV like '%Phần mềm%'
		or TenCV like '%ứng dụng%'
		or TenCV like '%Cloud%'
		or TenCV like '%Test%'
		or TenCV like 'QA %'
		or TenCV like '%QC%'
		or TenCV like '%Business Analyst%'
		or TenCV like '%Business Analyst'
		or TenCV like '%BA%'
		or TenCV like '%Công nghệ thông tin%'
		or TenCV like '%ABAP%'
--
		or TenCV like '%Solution%'
		or TenCV like '%Hệ thống%'
		or TenCV like '%bảo mật%'
		or TenCV like '%security%'
		or TenCV like '%hạ tầng%'
		or TenCV like '%quản trị mạng%'
--
		or TenCV like '%AI%'
		or TenCV like '%Analy%'
		or TenCV like '%Intelligence%'
		or TenCV like '% Data %'
		or TenCV like 'Data%'
	);
	-- Các CV sau 2 lần lọc không thuộc ngành nào sẽ được cho vào ngành IT Khác
		update Stg_ThongTin 
        set ID_Nganh = 6 
        where ID_Nganh is null;
END